# Generated by Django 5.0.6 on 2025-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Customer's phone number (e.g., +254712345678)",
                max_length=15,
                null=True,
            ),
        ),
    ]
