# Generated by Django 5.0.6 on 2025-06-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_order_products_customer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="old_products",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(through="core.OrderItem", to="core.product"),
        ),
    ]
